repos:
-   repo: https://github.com/lorenzwalthert/pre-commit-hooks
    rev: v0.3.2.9001
    hooks:
    -   id: style-files
    -   id: parsable-R
    -   id: no-browser-statement
    -   id: readme-rmd-rendered
    -   id: roxygenize
    -   id: use-tidy-description
    # -   id: lintr
